### ISSUE TITLE
太電拉

### ISSUE THREAD

**Issue by xiaoxigua-1** [xiaomiao-fong/Chen_bot#2]
# 扯爆電神開源

**Comment by xiaomiao-fong** [comment]
您

**Comment by xiaoxigua-1** [comment]
扯爆

**Comment by xiaomiao-fong** [comment]
你要鞭我的碼嗎

**Comment by xiaoxigua-1** [comment]
扯爆我都沒在寫

**Comment by xiaoxigua-1** [comment]
> 扯爆我都沒在寫

我都在寫網站

**Comment by xiaomiao-fong** [comment]
你都在寫更電的東西 djs你已經看不上了 🛐

**Comment by xiaoxigua-1** [comment]
> 你都在寫更電的東西 djs你已經看不上了 🛐

您

**Comment by xiaomiao-fong** [comment]
> > 你都在寫更電的東西 djs你已經看不上了 🛐
> 
> 您

您 我還在玩djs

**Comment by xiaoxigua-1** [comment]
> > > 你都在寫更電的東西 djs你已經看不上了 🛐
> > 
> > 
> > 您
> 
> 您 我還在玩djs

QQ我都不會

**Comment by xiaomiao-fong** [comment]
> > > > 你都在寫更電的東西 djs你已經看不上了 🛐
> > > 
> > > 
> > > 您
> > 
> > 
> > 您 我還在玩djs
> 
> QQ我都不會

電神都諷刺

**Comment by xiaoxigua-1** [comment]
> > > > > 你都在寫更電的東西 djs你已經看不上了 🛐
> > > > 
> > > > 
> > > > 您
> > > 
> > > 
> > > 您 我還在玩djs
> > 
> > 
> > QQ我都不會
> 
> 電神都諷刺

您吧我只會寫網站您都不教我怎麼寫其他東西

**Comment by xiaomiao-fong** [comment]
所以鞭嗎 🛐

**Comment by xiaomiao-fong** [comment]
> > > > > > 你都在寫更電的東西 djs你已經看不上了 🛐
> > > > > 
> > > > > 
> > > > > 您
> > > > 
> > > > 
> > > > 您 我還在玩djs
> > > 
> > > 
> > > QQ我都不會
> > 
> > 
> > 電神都諷刺
> 
> 您吧我只會寫網站您都不教我怎麼寫其他東西

我不會寫網站QQ

**Comment by hello1234316** [comment]
都電

**Comment by xiaoxigua-1** [comment]
> 所以鞭嗎 🛐

豪扯

**Comment by ChinHongTan** [comment]
好扯都用GitHub聊天QQ

**Comment by xiaoxigua-1** [comment]
> 都電

更電的出現ㄌ

**Comment by xiaomiao-fong** [comment]
笑死越來越多人了

**Comment by xiaomiao-fong** [comment]
電神大量出現

**Comment by xiaoxigua-1** [comment]
> > > > > > > 你都在寫更電的東西 djs你已經看不上了 🛐
> > > > > > 
> > > > > > 
> > > > > > 您
> > > > > 
> > > > > 
> > > > > 您 我還在玩djs
> > > > 
> > > > 
> > > > QQ我都不會
> > > 
> > > 
> > > 電神都諷刺
> > 
> > 
> > 您吧我只會寫網站您都不教我怎麼寫其他東西
> 
> 我不會寫網站QQ

都不按star 😠

**Comment by hello1234316** [comment]
> > 都電
> 
> 更電的出現ㄌ



> 電神大量出現

都因為Discord

**Comment by xiaoxigua-1** [comment]
> > > 都電
> > 
> > 
> > 更電的出現ㄌ
> 
> > 電神大量出現
> 
> 都因為Discord

扯爆

**Comment by hello1234316** [comment]
> > > > 都電
> > > 
> > > 
> > > 更電的出現ㄌ
> > 
> > 
> > > 電神大量出現
> > 
> > 
> > 都因為Discord
> 
> 扯爆

一坨大佬 🛐

**Comment by ChinHongTan** [comment]
好扯好扯大老遠過來就因為小喵電神

**Comment by xiaoxigua-1** [comment]
> 好扯好扯大老遠過來就因為小喵電神
我老了QQ

**Comment by xiaomiao-fong** [comment]
> 好扯好扯大老遠過來就因為小喵電神

我墊

**Comment by xiaoxigua-1** [comment]
> > 好扯好扯大老遠過來就因為小喵電神
> 
> 我墊

沒錯

**Comment by xiaomiao-fong** [comment]
QQ 佬們都嘲諷

**Comment by xiaoxigua-1** [comment]
> > > 好扯好扯大老遠過來就因為小喵電神
> > 
> > 
> > 我墊
> 
> 沒錯

只是是電

**Comment by ChinHongTan** [comment]
電爆

**Comment by xiaoxigua-1** [comment]
> QQ 佬們都嘲諷

您吧都嘲諷我都拿數學打我臉

**Comment by xiaomiao-fong** [comment]
QQ 您都寫網站 電我一臉

**Comment by xiaoxigua-1** [comment]
> QQ 您都寫網站 電我一臉

您吧我網站都好破QQ

**Comment by xiaomiao-fong** [comment]
椒麻

**Comment by xiaoxigua-1** [comment]
> 椒麻

😠 都嘲諷

**Comment by ChinHongTan** [comment]
好扯
越來越嘲諷了
還是先溜好了

**Comment by xiaomiao-fong** [comment]
真的拉 電神您都寫vue

> > 椒麻
> 
> 😠 都嘲諷

**Comment by xiaomiao-fong** [comment]
> 好扯
> 越來越嘲諷了
> 還是先溜好了

笑死

**Comment by xiaoxigua-1** [comment]
> 真的拉 電神您都寫vue
> 
> > > 椒麻
> > 
> > 
> > 😠 都嘲諷

😠 幾百年不寫vueㄌ

**Comment by xiaomiao-fong** [comment]
> > 真的拉 電神您都寫vue
> > > > 椒麻
> > > 
> > > 
> > > 😠 都嘲諷
> 
> 😠 幾百年不寫vueㄌ

更電了 所以你現在都寫啥

**Comment by xiaoxigua-1** [comment]
> > > 真的拉 電神您都寫vue
> > > > > 椒麻
> > > > 
> > > > 
> > > > 😠 都嘲諷
> > 
> > 
> > 😠 幾百年不寫vueㄌ
> 
> 更電了 所以你現在都寫啥

😠 您才電React

**Comment by xiaomiao-fong** [comment]
> > > > 真的拉 電神您都寫vue
> > > > > > 椒麻
> > > > > 
> > > > > 
> > > > > 😠 都嘲諷
> > > 
> > > 
> > > 😠 幾百年不寫vueㄌ
> > 
> > 
> > 更電了 所以你現在都寫啥
> 
> 😠 您才電React

所以vue 還有 react您推哪個

**Comment by xiaoxigua-1** [comment]
> > > > > 真的拉 電神您都寫vue
> > > > > > > 椒麻
> > > > > > 
> > > > > > 
> > > > > > 😠 都嘲諷
> > > > 
> > > > 
> > > > 😠 幾百年不寫vueㄌ
> > > 
> > > 
> > > 更電了 所以你現在都寫啥
> > 
> > 
> > 😠 您才電React
> 
> 所以vue 還有 react您推哪個

我自己喜歡React OAO

**Comment by xiaomiao-fong** [comment]
OAO

**Comment by xiaomiao-fong** [comment]
電

**Comment by xiaoxigua-1** [comment]
Vue對我來說有點像大雜燴
css js html塞在一起QQ

**Comment by xiaomiao-fong** [comment]
我不會css QQ

**Comment by xiaoxigua-1** [comment]
> 電

您

**Comment by ChinHongTan** [comment]
感覺vue比較好玩？
React有點看不懂

**Comment by xiaoxigua-1** [comment]
> 感覺vue比較好玩？
> React有點看不懂

🤔 佬

**Comment by xiaomiao-fong** [comment]
🤔

**Comment by xiaoxigua-1** [comment]
React Hook因該相對於以前的class寫法應該很好懂ㄌ

**Comment by xiaoxigua-1** [comment]
> React Hook因該相對於以前的class寫法應該很好懂ㄌ

🤔

**Comment by xiaomiao-fong** [comment]
聽起來都好電

**Comment by xiaoxigua-1** [comment]
> 聽起來都好電

您吧都這樣QQ

**Comment by ChinHongTan** [comment]
明天有時間深入一點研究一下好了

**Comment by ChinHongTan** [comment]
明天有時間深入一點研究一下好了

**Comment by xiaoxigua-1** [comment]
> 明天有時間深入一點研究一下好了

電

**Comment by xiaomiao-fong** [comment]
佬

**Comment by xiaoxigua-1** [comment]
幫貓貓的repo創造討論度 U

**Comment by xiaomiao-fong** [comment]
U

**Comment by ChinHongTan** [comment]
關掉啦還U XDDD
